### ISSUE TITLE
Extend plugin with Markdown/reST admonitions

### ISSUE THREAD

**Issue by nuest** [chdemko/pandoc-latex-admonition#1]
Hi! I'm trying to convert Markdown based documentation (using [mkdocs](http://www.mkdocs.org/)) into a PDF using [mkdocs2pandoc](https://github.com/jgrassler/mkdocs-pandoc). In the Markdown I'm heavily using the [markdown admonitions](https://pythonhosted.org/Markdown/extensions/admonition.html) extension, creating markup such as

```markdown
!!! note
    This is a note.

!!! warning
    This version is _under development_!
```

for which the latter in pandocs native format would be

```
,Para [Str "!!!",Space,Str "warning",SoftBreak,Str "This",Space,Str "version",Space,Str "is",Space,Emph [Str "under",Space,Str "development"],Str "!"]
```

I think it would be great if your plugin would also detect these kinds of admonitions, too. The [detection](https://github.com/chdemko/pandoc-latex-admonition/blob/master/pandoc_latex_admonition.py#L22) probably needs to work a bit different, maybe something like `if key == 'Para' and value.startsWith("!!!)>` ?

If you don't have any value from this proposal yourself, I'd be happy to give it a try to extend this plugin if you think this actually fits here.

Thanks for your feedback!

**Comment by nuest** [comment]
Thinking about this again, the issue is rather that I do not have `div`s, but only admonition blocks. Maybe a pre-filtering converting the admonitions to HTML could solve this.

**Comment by chdemko** [comment]
The better for you would be to write a filter that surroud a paragraph beginning with !!! by a div

**Comment by chdemko** [comment]
You could also use new div notation. See http://pandoc.org/MANUAL.html#extension-fenced_divs
