### ISSUE TITLE
Triple exclamation mark

### ISSUE THREAD

**Issue by ManuelSelva** [chdemko/pandoc-latex-admonition#10]
Hi,

I have a markdown file with things like : 
```
!!! question "Question 1"
``` 
That are properly rendered in web pages generated using `mkdocs`.
Now I also want to generate pdf files from the same markdown.

I installed your filter and ran the following command : 
```
 pandoc --filter pandoc-latex-admonition README.md -o test.pdf
```
Unfortunately, the triple exclamation mark has not been processed and is then just rendered as text.

Looking at your example file, I am not sure your filter should help me to achieve my goal. Do you confirm ? Can you help me on that ?

Thank you very much in advance for your help

**Comment by chdemko** [comment]
!!! is not in the pandoc syntax...
