### ISSUE TITLE
Add example of syntax for admonition and an eventual rendered/displayed admonition in .pdf

### ISSUE THREAD

**Issue by bartvanderwal** [chdemko/pandoc-latex-admonition#11]
Could you add to the README:

1. An **example of a working admonition**. I find in the issues that for instance `!!! info` is NOT the pandoc syntax, but the responder doesn't specify WHAT IS the pandoc way. This might be stating the obvious for true 'pandocians', but for people googling around for solutions like me this would be very useful/productive.

2. Even more useful for potential users would be to see an **example of a rendered admonition** (typically for the previously provided example). For instance in a .pdf. I understand that there are endless possibilities. But generally people are looking for a solution that looks good/decent 'out of the box'.

I'll see if I can get this running for myself and provide both here in this issue.

And possibly do a pull request on an updated `README.md`, but I'm pretty busy so can't make any promises.

**Comment by chdemko** [comment]
There is an example in the docs (link in the readme) that explain how to use this filter.
