### ISSUE TITLE
Environment not found

### ISSUE THREAD

**Issue by nuest** [chdemko/pandoc-latex-admonition#2]
I have a problem using this filter, as the default environment (defined [here](https://github.com/chdemko/pandoc-latex-admonition/blob/master/pandoc_latex_admonition.py#L40)) is not found when the latex is rendered. 

```
(/home/travis/texlive/texmf-dist/tex/generic/oberdiek/gettitlestring.sty))! LaTeX Error: Environment env-9cd35787-c1e2-482d-b7c4-dfc77d8bcaa0 undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                        
l.211 ...env-9cd35787-c1e2-482d-b7c4-dfc77d8bcaa0}

pandoc: Error producing PDF from TeX source
```

You can find the whole LaTeX document in the Travis build log starting [in this line](https://travis-ci.org/o2r-project/erc-spec/builds/298949395#L1205)

The admonition configuration is [this file](https://github.com/o2r-project/erc-spec/blob/master/docs/admonition_config.yml)

The pandoc command is [here](https://github.com/o2r-project/erc-spec/blob/master/Makefile#L34)

I appreciate any pointer.

**The issue seems to be that the environments are not defined.** There is not environment definition in the LaTeX header.

I also do not find where the function `defaultEnvironment` is (supposed to be) called.

**Comment by chdemko** [comment]
Could you please post your markdown file (or an example that do not work)

**Comment by nuest** [comment]
Thanks for replying. The problem is that I cannot reproduce the issue locally, it only exists on Travis. And it is the weirdest thing:

This file does _not_ work: https://github.com/o2r-project/erc-spec/blob/7bb7b52a8176b0068bca6795643d343f2e4140a6/erc.pd

But this one does: https://github.com/o2r-project/erc-spec/blob/3101297232bbb351a84914e109e24e4674cc91fc/erc.pd

The only difference are some empty lines and the working document has ~ 70 lines more at the beginning, see this diff: https://github.com/o2r-project/erc-spec/commit/7bb7b52a8176b0068bca6795643d343f2e4140a6#diff-f0da4ae805b5477f2ff46835d9c69682

**Comment by chdemko** [comment]
Check if the pandoc version on travis...

~~~
pandoc -v
~~~

**Comment by chdemko** [comment]
No more comments on this issue. Closing it.
