### ISSUE TITLE
Undefined control sequence

### ISSUE THREAD

**Issue by ghost** [chdemko/pandoc-latex-admonition#4]
Adding `--filter pandoc-latex-admonition` causes the following error:

```
Error producing PDF.
tex error       > tex error on line 88 in file /home/USR/PRJ/DIR/tex2pdf.-a8dc7ed47183d119/input.tex: ! Undefined control sequence
```

which corresponds to this line:

```
\usepackage{mdframed}
```

`mdframed` is installed:

```
➜ ls -l /usr/share/texmf-dist/tex/latex/mdframed/mdframed.sty
-rw-r--r-- 1 root root 53487 Sep  5 00:17 /usr/share/texmf-dist/tex/latex/mdframed/mdframed.sty
```

If I swap `\usepackage{mdframed}` with the following line, `\usepackage{xcolor}`, I get the same error on the same line.  I haven't used TeX directly in decades; how can I check that `pandoc-latex-admonition` is generating the right TeX instructions at the right place?

**Comment by chdemko** [comment]
You can run pandoc for generating tex file:

~~~bash
$ pandoc -s --filter pandoc-latex-admonition source.md -o source.tex
~~~

**Comment by chdemko** [comment]
Could you post the file in error somewhere for testing?

**Comment by ghost** [comment]
I decided that this was because I use the context backend. Although I'm not sure why it doesn't work (context is like latex, a set of TeX extensions, right?) I'm willing to assume there's some basic incompatibility.   I'll close this if that's the case.
