### ISSUE TITLE
Use Latex to build PDF and deploy it from travis

### ISSUE THREAD

**Issue by edusantana** [chdemko/pandoc-latex-admonition#5]
- [.travis.yml](https://github.com/abntex/limarka/blob/master/.travis.yml)
- [installing tinytex at travis](https://github.com/abntex/limarka/blob/master/bin/instalador.sh)
- [depoy to github releases](https://github.com/abntex/trabalho-academico-limarka/blob/master/.travis.yml#L16-L21)

I use a project with latex and travis, if we use travis to build it makes more clean which packges we need to build it. I also use travis cache, to avoid install tinytex every time. If you need help, i'm here.

For me, to use this filter I had to install other packages: `tlmgr install tcolorbox xcolor mdwtools pgf environ trimspaces`. And it produces this [t.pdf](https://github.com/chdemko/pandoc-latex-admonition/files/3345706/t.pdf)

**Comment by chdemko** [comment]
Do you have any issues with pandoc-latex-admonition?

**Comment by edusantana** [comment]
I had. I was using [tinytext](https://yihui.name/tinytex/) instead of texlive. The project [README](https://github.com/chdemko/pandoc-latex-admonition/blame/master/README.md#L57-L64) says nonexistent packages like `ifthen` (this is not a valid package).

My suggestion is to add these packages to your README(`tcolorbox xcolor mdwtools pgf environ trimspaces`).

And if you would like to make sure, I can help you to change `.travis` so you can see youself.

**Comment by chdemko** [comment]
You can propose a [PR](https://github.com/chdemko/pandoc-latex-admonition/pulls)
