### ISSUE TITLE
Cannot reproduce compiling sample file

### ISSUE THREAD

**Issue by chrisothal** [chdemko/pandoc-latex-admonition#7]
I receive an error producing a PDF when I try to compile the [sample file](https://raw.githubusercontent.com/wiki/chdemko/pandoc-latex-admonition/images/pandoc-latex-admonition-sample.txt) directly to a PDF using the command `pandoc -s -o pandoc-latex-admonition-sample.pdf --filter pandoc-latex-admonition pandoc-latex-admonition-sample.txt`

    Error producing PDF.
    ! Extra }, or forgotten \endgroup.
    <argument> ...@finalstrut \strutbox }\fn@endnote }
    
    l.290 ...sent\footnote{Praesent non fringilla leo}

If I convert to a .tex intermediate file and then convert the .tex to a PDF, I do not see the tcolorbox bar.
![image](https://user-images.githubusercontent.com/29053059/64456708-dfe1ed80-d0be-11e9-992a-478ec1637b9c.png)

**Comment by chdemko** [comment]
what is your pandoc version? and what is the content of the sample file?
